#!/usr/bin/env sh

# Original idea: https://github.com/davidguttman/simplify-gmail-native/blob/master/install.sh

source helpers.zsh

if _not_installed "npm"; then
  _pp_error "gmail" "npm is required, please install it first."
  exit 1
fi

_pp_info "gmail" "installing dependencies..."
npm install

_pp_info "gmail" "compiling custom Simplify extension..."


set -e
npm run build
set +e

cp simplify/style.css dist/style.css

sed -i '' '/var simplSettings =/{
s/.*//g
r overrides/settings.js
}' dist/script.js

_pp_info "gmail" "building custom version of Gmail..."

nativefier "https://mail.google.com/mail" \
   --title-bar-style 'hiddenInset' \
   --disable-gpu \
   --platform "mac" \
   --arch "x64" \
   --electron-version 2.0.2 \
   --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' \
   --internal-urls ".*accounts .google.com.*" \
   -i imgs/gmail.icns \
   --inject dist/style.css \
   --inject dist/script.js

_pp_info "gmail" "moving generated .app to /Applications"
mv 'Gmail-darwin-x64'/'Gmail.app' /Applications

_pp_info "gmail" "cleaning up..."
rm -r 'Gmail-darwin-x64'
rm -r dist

_pp_success "gmail" "great success!"
